name: CI Build Log Example

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build and save logs
        run: |
          mkdir -p build
          bash scripts/build.sh 2>&1 | tee build/build.log

      - name: Verify build log exists
        run: test -f build/build.log

      - name: Upload build log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build/build.log
