name: CI Build Log Example

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List files in the repository (debugging)
        run: ls -R

      - name: Run Build Script and Save Logs
        run: |
          mkdir -p build
          bash scripts/build.sh 2>&1 | tee build/build.log

      - name: Upload Build Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build/build.log
