name: CI Build with Unit Tests and Test Logs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install  # or other package manager like pip, yarn, etc.

      - name: Upload Test Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
            name: test-log-${{ github.sha }}
            path: github-actions/shared/test.log

